### ISSUE TITLE
rake task won't execute

### ISSUE THREAD

**Issue by samstickland** [state-machines/state_machines-graphviz#6]
Hi,

I have state_machines-graphviz 0.0.2 installed, and the task shows up in the list:

```
$ rake -T | grep state
rake state_machines:draw                               # Draws state machines using GraphViz (options: CLASS=User,Vehicle; FILE=user.rb,vehicle.rb [not required in Rails / Merb]; FONT=Arial; FORMAT=png; ORIENTATION=portrait; HUMAN_NAMES=true
```

But when I try to execute the task it doesn't work:

```
$ rake state_machines:draw CLASS=Company
rake aborted!
Don't know how to build task 'state_machines:draw'

(See full trace by running task with --trace)
```

Here's a full trace:

```
$ rake state_machines:draw CLASS=Company --trace
rake aborted!
Don't know how to build task 'state_machines:draw'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task_manager.rb:62:in `[]'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:149:in `invoke_task'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/dev/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/dev/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
```

**Comment by rosskevin** [comment]
Confirmed, I see the same thing on my end.  I'm guessing it's a problem with the `Railtie` or requires.  I don't have time to look at it right now as I'm preparing to be out for a few days.  If you can take a look and solve it, we would welcome a pull request.

**Comment by rosskevin** [comment]
A helpful pull would have a `spec/dummy` rails app, if you so happen to have the time and energy :)  

When we ported the code, it didn't have that test so that would prevent this sort of thing from happening again.

**Comment by seuros** [comment]
I take this one. I have to remove rspec and replace it with minitest.

**Comment by bram70** [comment]
Hi all, I tried to fix this issue, but I wasn't able to reproduce it. Can you try it now?
